### ISSUE TITLE
Grabbing PFP element name

### ISSUE THREAD

**Issue by VillainsRule4000** [qaiik/betastarapidocs#1]
If I wanted to write a script that essentially found my element/PFP name, how would I do that?

**Comment by qaiik** [comment]
That would be a simple fetch request to https://betastar.org/api/user/.

Here is some code:
```js
fetch("https://betastar.org/api/user/").then(res=>res.json()).then(data=>{
    console.log(data.element)
}
```

**Comment by VillainsRule4000** [comment]
Thanks!
